[package]
name = "is_dark_mode_server"
version = "1.0.0"
edition = "2021"
authors = ["Nikita Patskov <patskovn@gmail.com>"]
description = "Tiny webserver to deremine dark mode state"
license = "MIT"

[dependencies]
